# Generated by Django 4.1.3 on 2022-11-15 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="participate",
        ),
    ]
