# Generated by Django 4.1.3 on 2022-11-10 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="time",
            field=models.CharField(
                choices=[
                    ("15:00", "15:00"),
                    ("06:00", "06:00"),
                    ("19:00", "19:00"),
                    ("20:00", "20:00"),
                    ("18:00", "18:00"),
                    ("17:00", "17:00"),
                    ("16:00", "16:00"),
                    ("07:00", "07:00"),
                    ("12:00", "12:00"),
                    ("21:00", "21:00"),
                    ("08:00", "08:00"),
                    ("22:00", "22:00"),
                    ("09:00", "09:00"),
                    ("11:00", "11:00"),
                    ("10:00", "10:00"),
                    ("14:00", "14:00"),
                    ("13:00", "13:00"),
                ],
                max_length=20,
            ),
        ),
    ]
