# Generated by Django 4.1.3 on 2022-11-16 02:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Park",
        ),
    ]
