# Generated by Django 4.1.3 on 2022-11-15 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Park",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(blank=True, max_length=300, null=True)),
                ("name", models.CharField(blank=True, max_length=300, null=True)),
                ("parktype", models.CharField(blank=True, max_length=300, null=True)),
                ("addr1", models.CharField(blank=True, max_length=300, null=True)),
                ("add2", models.CharField(blank=True, max_length=300, null=True)),
                ("lat", models.CharField(blank=True, max_length=300, null=True)),
                ("long", models.CharField(blank=True, max_length=300, null=True)),
                ("size", models.CharField(blank=True, max_length=300, null=True)),
                (
                    "facility_sport",
                    models.CharField(blank=True, max_length=300, null=True),
                ),
                (
                    "facility_game",
                    models.CharField(blank=True, max_length=300, null=True),
                ),
                (
                    "facility_con",
                    models.CharField(blank=True, max_length=300, null=True),
                ),
                (
                    "facility_edu",
                    models.CharField(blank=True, max_length=300, null=True),
                ),
                (
                    "facility_other",
                    models.CharField(blank=True, max_length=300, null=True),
                ),
                ("establish", models.CharField(blank=True, max_length=300, null=True)),
                ("manage_org", models.CharField(blank=True, max_length=300, null=True)),
                ("tel", models.CharField(blank=True, max_length=300, null=True)),
                ("created_at", models.CharField(blank=True, max_length=300, null=True)),
                ("org_code", models.CharField(blank=True, max_length=300, null=True)),
                ("org_name", models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
    ]
