# Generated by Django 3.2.13 on 2022-11-17 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_chat'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Chat',
        ),
    ]
