# Generated by Django 3.2.13 on 2022-11-17 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_post_post_hit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='parent_comment',
        ),
        migrations.RemoveField(
            model_name='post',
            name='post_hit',
        ),
        migrations.AlterModelTable(
            name='comment',
            table=None,
        ),
    ]
