# Generated by Django 4.1.3 on 2022-11-15 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0003_remove_park_org_code_remove_park_org_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="park",
            name="add2",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="park",
            name="addr1",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="park",
            name="code",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="park",
            name="lat",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="park",
            name="long",
            field=models.FloatField(),
        ),
    ]
