# Generated by Django 3.2.13 on 2022-11-17 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20221117_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='hit',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
