# Generated by Django 4.1.3 on 2022-11-10 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="age",
            field=models.IntegerField(default=25),
        ),
        migrations.AlterField(
            model_name="user",
            name="manner_point",
            field=models.DecimalField(decimal_places=1, default=36.5, max_digits=4),
        ),
    ]
