# Generated by Django 4.1.3 on 2022-11-11 02:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="age",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 11, 11, 11, 56, 11, 434198)
            ),
        ),
    ]
