# Generated by Django 4.1.3 on 2022-11-10 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="age",
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
