# Generated by Django 4.1.3 on 2022-11-10 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_user_age_alter_user_manner_point"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="age",
            field=models.IntegerField(default=18),
        ),
    ]
