# Generated by Django 4.1.3 on 2022-11-10 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_user_age"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="manner_point",
            field=models.DecimalField(decimal_places=1, default=36.5, max_digits=1),
        ),
    ]
