# Generated by Django 4.1.3 on 2022-11-11 09:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_user_age"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="age",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
