# Generated by Django 4.1.3 on 2022-11-11 00:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_user_manner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="age",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 11, 11, 9, 46, 33, 942267)
            ),
        ),
    ]
