# Generated by Django 3.2.13 on 2022-11-19 13:50

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=imagekit.models.fields.ProcessedImageField(blank=True, default='../static/images/profile_default.png', upload_to='profile/%Y%m%d/'),
        ),
    ]
