# Generated by Django 3.2.13 on 2022-11-17 01:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_manner_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='blocking',
            field=models.ManyToManyField(related_name='blockers', to=settings.AUTH_USER_MODEL),
        ),
    ]
